[package]
name = "adder"
version = "0.1.0"
authors = ["nativestranger <eric.ed.arnold@gmail.com>"]
edition = "2018"

[dependencies]

add-one = { path = "../add-one" }
add-two = { path = "../add-two" }
